services:
  - type: web
    name: packers-movers-backend
    runtime: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/packers-movers-0.0.1-SNAPSHOT.jar

    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION_TIME
        value: "72000000000"